### ISSUE TITLE
Scanner crushes immediately on ionic 6 app

### ISSUE THREAD

**Issue by cool-projects** [Ratsoc/cordova-plugin-firebase-ml-kit-barcode-scanner#7]
My app crushes immediately after attempting to launch scanner. This is on ionic 6 app. Cordova v10.

**Comment by imrranbadshah** [comment]
@cool-projects 
Add this line in config.xml file 
   ` <preference name="GradlePluginGoogleServicesEnabled" value="true" />`
and also add `google_services.json` file inside `platform/android/app` and also inside `platform/android/app/src`.
This worked for me :)

**Comment by ravimarellatieto** [comment]
> @cool-projects
> 
> Add this line in config.xml file ` <preference name="GradlePluginGoogleServicesEnabled" value="true" />` and also add `google_services.json` file inside `platform/android/app` and also inside `platform/android/app/src`. and also allow for camera permission. This worked for me :)

Hi
Could you please help me in finding the google_services.json file? Its not there in the git repository. Do I have to create a new project/ app in firebase and download the json from there. If so, does the package name have to be same as the plugin or can it be anything.
